version: "3.9"
services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000" # Porta para acessar o backend
    volumes:
      - ./:/app # Para desenvolvimento (hot reload)
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: